### PR TITLE
feat: boba added back in to dropdown.

### PR DESCRIPTION
**Pull request by Tulun**
Signed-off-by: Tulun <jaykiraly@gmail.com>

### CODE REVIEW

**Comment by daywiss** [comment]
image

**Comment by daywiss** [comment]
eth is also missing from the dropdown, is that expected?

**Comment by Tulun** [comment]
> image

This is probably expected, as the bridge address is undefined.

**Comment by Tulun** [comment]
> eth is also missing from the dropdown, is that expected?

Possibly, I couldn't find a WETH address in their lists of contracts.

**Comment by daywiss** [comment]
> eth is also missing from the dropdown, is that expected?
> 
> Possibly, I couldn't find a WETH address in their lists of contracts.

[This](https://blockexplorer.boba.network/tokens) has a more exhaustive list of tokens vs their docs. 
 This is what weth should be ( think) `0xDeadDeAddeAddEAddeadDEaDDEAdDeaDDeAD0000`

**Comment by daywiss** [comment]
also we have boba the erc20 enabled, i dont think we can bring that across

**Comment by Tulun** [comment]
> also we have boba the erc20 enabled, i dont think we can bring that across

Ok! I'll make these adjustments.

**Review by daywiss — APPROVED** [review]

**Pull request merged**
