### PR TITLE
fix(across): reconcile toChain with currentlySelectedToChain

### PR DESCRIPTION
**Pull request by Gamaranto**
**Motivation**

This PR various bugs and cleans up the codebase by reducing data structures, making the existing ones more flexible and improved error handling.

**Summary**

This PR mainly does 3 things:
- Reconcile the currentlySelectedTo/FromChain with the from/toChain state slices
- Introduce a "reachable" chain array to the CHAINS_LIST record that allows us to more easily show chains that can be reached from where
- Change the code across the dapp to work with the above

**Details**

**Testing**

Check a box to describe how you tested these changes and list the steps for reviewers to test.

- [ ]  Ran end-to-end test, running the code as in production
- [ ]  New unit tests created
- [ ]  Existing tests adequate, no new tests required
- [ ]  All existing tests pass
- [x]  Untested

**Issue(s)**

N/A

### CODE REVIEW

**Comment by daywiss** [comment]
theres a way to select uma on boba:
image

1. Select optimism from
2. select uma asset
3. switch to boba from
4. see that uma is still selected and you can enter amount

**Comment by Gamaranto** [comment]
> theres a way to select uma on boba: image
> 
> 1. Select optimism from
> 2. select uma asset
> 3. switch to boba from
> 4. see that uma is still selected and you can enter amount
> 
> this was fixed in #113

good catch thank you

**Comment by daywiss** [comment]
image
I got the UI to a weird state

dont know repro steps yet

**Comment by daywiss** [comment]
getting a error in console when switching to eth

1. select and connect to optimism
2. switch to eth in from dropdown
3. see error in console
4. 
image

**Comment by daywiss** [comment]
You can send an approval even though you are on wrong network
1. select and connect to optimism
2. select from eth
3. hit max
4. see that you can send approval 

image

**Comment by daywiss** [comment]
issue with displaying usdc when eth is selected: 
image

**Comment by daywiss** [comment]
seeing an error in console when switching from mainnet to optimism:
image

1. select and connect to ethereum
2. switch from optimism, connect optimism
3. see error in console

**Comment by daywiss** [comment]
going to close this until we have time to come back to it

**Pull request closed without merging**
