### PR TITLE
Add Tally intergration

### PR DESCRIPTION
**Pull request by 0xzoz**
Add support for [Tally](https://tally.cash/) wallet. Tally is an open-source browser extension similar to Metamask.

### CODE REVIEW

**Review by Gamaranto — COMMENTED** [review]
code looks good, waiting for QA

**Comment by Tommy1231232** [comment]
@0xzoz We'd love to support Tally! It looks like the way this is implemented isn't designed the best. Can you structure it per the attached designs (please include the tally logo as an icon). 

Also attaching what the current view looks like (which is [incorrect)](url)

Current view in PR
Current view 2 in PR
Designs

**Comment by 0xzoz** [comment]
Thanks for pointing this out @Tommy1231232 .  This has been rectified and now displays as per the structure above

**Review by daywiss — APPROVED** [review]
lgtm, @Gamaranto what do u think?

**Comment by Tommy1231232** [comment]
> 

@0xzoz looks amazing. Our designer had one small comment before we merge: "The word “Tally” should be center aligned like Metamask"

Excited to get this in master!
"

**Comment by 0xzoz** [comment]
Thanks @Tommy1231232. I have aligned the text center. Apologies, wasnt sure if it was neccesary

**Review by Gamaranto — APPROVED** [review]

**Comment by 0xzoz** [comment]
@Tommy1231232 @Gamaranto we are doing a co-marketing push for the Tally wallet release on the 11/04/2022. This would allow users of your app to claim an airdrop. Who is the best person to reach out to for this? I can be contacted on discord at zoz.eth#6952

**Pull request merged**
